{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/{{.Values.rbac.apiVersion }}
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "vault-etcd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.component }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "vault-etcd.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "vault-etcd.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "vault-etcd.fullname" . }}
{{- end }}