{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "vault-etcd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.component }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "vault-etcd.fullname" . }}
{{- end }}