---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "vault-etcd.fullname" . }}
  labels:
    app: {{ template "vault-etcd.name" .}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.component }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "vault-etcd.fullname" . }}
  replicas: {{ default 3 .Values.service.replicas }}
  template:
    metadata:
      name: {{ template "vault-etcd.fullname" . }}
      labels:
        app: {{ template "vault-etcd.fullname" . }}
        release: {{ .Release.Name }}
        component: "{{ .Release.Name }}-{{ .Values.component }}"
    spec:
      terminationGracePeriodSeconds: {{ .Values.service.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "vault-etcd.fullname" . }}
        image: "{{ .Values.image.source }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.peerPort }}
          name: peer
        - containerPort: {{ .Values.service.clientPort }}
          name: client
        resources:
          requests:
            cpu: {{ .Values.service.cpu }}
            memory: {{ .Values.storage.size }}
        env:
        - name: INITIAL_CLUSTER_SIZE
          value: {{ default 3 .Values.service.replicas | quote }}
        - name: SET_NAME
          value: {{ template "vault-etcd.fullname" . }}
        - name: DATA_DIR
          value: {{ .Values.DataDir }}
        - name: ETCD_PEER_PORT
          value: {{ .Values.service.peerPort | quote}}
        - name: ETCD_CLIENT_PORT
          value: {{ .Values.service.clientPort | quote}}
        volumeMounts:
        - name: {{ .Values.storage.mount }}
          mountPath: {{ .Values.service.dataDir }}
        - name: config
          mountPath: /etcd-bin/etcd-start.sh
          subPath: etcd-start.sh
          readOnly: false
        - name: config
          mountPath: /etcd-bin/lifecycle-prestop.sh
          subPath: lifecycle-prestop.sh
          readOnly: false
        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/sh"
                - "/etcd-bin/lifecycle-prestop.sh"
        command:
          - "/bin/sh"
          - "/etcd-bin/etcd-start.sh"
      volumes:
      - name: config
        configMap:
          name: {{ template "vault-etcd.fullname" . }}

  volumeClaimTemplates:
  - metadata:
        name: {{ .Values.storage.mount }}
    spec:
      storageClassName: "{{ .Values.storage.storageClass }}"
      accessModes:
{{ toYaml .Values.storage.accessModes | indent 8 }}
      resources:
        requests:
          storage: "{{ .Values.storage.size }}"
